language: node_js
node_js:
  - "node"
services:
  - mysql
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('password') where User='root';FLUSH PRIVILEGES;"
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
before_script:
  - npm install tsc -g
  - npm install
  - node -v
script:
  - npm run build-ts
  - npm run tslint
  - npm test
